# Generated by Django 5.0.6 on 2026-09-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Аты')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Email')),
                ('text', models.TextField(max_length=5000, verbose_name='Хабарлама')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Келген уақыты')),
                ('is_read', models.BooleanField(default=False, verbose_name='Оқылды')),
            ],
            options={
                'verbose_name': 'Хабарлама',
                'verbose_name_plural': 'Хабарламалар',
                'ordering': ['-created_at'],
            },
        ),
    ]
