# Generated by Django 5.0.6 on 2026-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Атауы')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('status', models.CharField(choices=[('live', 'Жұмыс істеп тұр'), ('done', 'Аяқталды'), ('wip', 'Жасалып жатыр')], default='done', max_length=10, verbose_name='Күйі')),
                ('tags', models.CharField(blank=True, help_text='Үтірмен бөліп жаз. Мысалы: Python, Django, SQLite', max_length=240, verbose_name='Технологиялар')),
                ('image', models.CharField(blank=True, help_text='images/ папкасындағы файлдың аты. Мысалы: project-1.jpg', max_length=160, verbose_name='Сурет файлы')),
                ('link', models.URLField(blank=True, help_text='GitHub немесе жобаның адресі', verbose_name='Сілтеме')),
                ('order', models.PositiveIntegerField(default=0, help_text='Кіші сан — жоғары тұрады', verbose_name='Реті')),
                ('is_published', models.BooleanField(default=True, verbose_name='Сайтта көрінсін')),
            ],
            options={
                'verbose_name': 'Жоба',
                'verbose_name_plural': 'Жобалар',
                'ordering': ['order', 'id'],
            },
        ),
    ]
