# Generated by Django 5.0.6 on 2026-09-14 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('slug', models.SlugField(blank=True, help_text='Бос қалдырсаң, тақырыптан автоматты жасалады.', max_length=90, unique=True, verbose_name='Сілтеме')),
                ('summary', models.TextField(help_text='Тізімде көрінетін 1–2 сөйлем.', max_length=400, verbose_name='Қысқаша')),
                ('body', models.TextField(help_text='Markdown: ## тақырып, - тізім, **қалың**, [мәтін](сілтеме), ![сурет](images/x.jpg)', verbose_name='Мәтін')),
                ('cover', models.CharField(blank=True, help_text='images/ ішіндегі файл аты. Мысалы: post-1.jpg', max_length=160, verbose_name='Мұқаба суреті')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Жарияланған күні')),
                ('is_published', models.BooleanField(default=True, verbose_name='Сайтта көрінсін')),
            ],
            options={
                'verbose_name': 'Жазба',
                'verbose_name_plural': 'Жазбалар',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
